.TH arachne 1 2009-Jul "linux" "heatherly custom tools manual"

.SH NAME
arachne \- wicked, versitle, and useful hexapod simulator/visualizer

.SH DESCRIPTION (short)
arachne is custom-built from the bottom-up to simulate, review, test, and
validate a frightening array of hexapod/spider robot movements.  this is a
lynch-pin application for my robotics.


hexapod robotics are wickedly complex and graceful results are almost impossible
for mere mortals.  arachne is custom-built from the bottom-up to review,
test, and validate a frightening array of hexapod/spider robot movements.
this is a lynch-pin application for my robotics.
